### ISSUE TITLE
Update install profile to work with latest D8 beta

### ISSUE THREAD

**Issue by joesb** [wunderkraut/wunderhub#23]
site.make at hub.wunder.io is set to install on Drupal 8.0.0-beta4, but [current D8 beta is 8.0.0-beta14](https://www.drupal.org/project/drupal)*.

\* subject to change :wink: 

We need to update the WK hub profile and modules to work with latest updates to D8.

**Comment by lewisnyman** [comment]
Drupal 8.0.x now supports upgrade paths, if we get it up and running on beta-14 then we are not going to have this much trouble again

**Comment by joesb** [comment]
Cool, good news. I'll get cracking on rebuilding in beta14, and see where I get.

**Comment by joesb** [comment]
WunderHub is now running on Drupal 8.0.0, all updates in place.
