### ISSUE TITLE
Move to deployment with Composer

### ISSUE THREAD

**Issue by joesb** [wunderkraut/wunderhub#43]
Currently we're using :grimacing: drush .make files, but it'd be great to switch stuff around to use Composer instead.

**Comment by joesb** [comment]
So this just about adding a composer.json file in the root directory, right? But what should go in that composer.json file?

I guess something along these lines would be a good start …

``` json
{
  "name": "wunderkraut/wunderhub",
  "description": "WunderHub site profile with Wundersites modules and settings",
  "type": "drupal-profile-custom",
  "homepage": "https://github.com/wunderkraut/wunderhub",
}
```

Comments, anyone?

**Comment by joesb** [comment]
I'm particularly unsure about that 'type' section - not sure about the format for that.

I guess something will need to be added to https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L36-L43 when you install to include an extra 'type' - how have you done this, @floretan ?

**Comment by joesb** [comment]
Aah, I've found https://www.drupal.org/project/composer_generate - maybe that'll help?

**Comment by joesb** [comment]
Nope, not 8.x compatible. Ah well.

**Comment by pixelmord** [comment]
We converted a couple of projects to the composer workflow already, so I can take a stab at this.

**Comment by pixelmord** [comment]
Sorry that was a bit hasty, I thought this issue was targeted at making the main codebase composer ready, but you are right: we need to investigate how to identify this project as a profile, not a module.

**Comment by pixelmord** [comment]
According to this [documentation page](https://www.drupal.org/node/2514612) you need to specify "drupal-profile"

**Comment by pixelmord** [comment]
See PR:
https://github.com/wunderkraut/wunderhub/pull/48

**Comment by joesb** [comment]
System no deployed at [hub.wunder.io](https://hub.wunder.io/) is now built with Composer - yay!
