### ISSUE TITLE
Record people’s skills and interests

### ISSUE THREAD

**Issue by joesb** [wunderkraut/wunderhub#53]
record people’s skills and interests - ideally with a weight on each one so we now what level they’re at. would display on the site as a tag cloud

from @steveparks

**Comment by joesb** [comment]
This is now deployed.

**Comment by joesb** [comment]
An example usage of this, for future reference:

http://lemberg.co.uk/devices-for-qa

**Comment by lewisnyman** [comment]
I've been thinking about this recently, as I've been trying to assess my own skill set that falls under one big umbrella of "UX" or "design". The current resources spreadsheet makes it really difficult to understand my knowledge, experience, and which areas I need to improve in.

Do you think it's worth having a bit of a think together about how we can make this feature more useful and prototyping something?

**Comment by joesb** [comment]
This is being talked about a bit in the Bank of Profiles internal project - maybe worth joining the HipChat room associated with that and joining the discussion there. @huberfl and @floretan and @WunderLemon and Merle Randlepp are part of the conversation there.
