### ISSUE TITLE
Evaluate using CORS instead of JSONP

### ISSUE THREAD

**Issue by pcambra** [wunderkraut/wunderhub#7]
We're using this approach: https://www.drupal.org/node/2132779 for supporting a JSONP call, but using CORS seems like a better approach if it reaches core at some point: https://www.drupal.org/node/1869548

Contrib module: https://github.com/previousnext/drupal_cors

**Comment by yannickoo** [comment]
Can we close this issue as well? I mean CORS is fixed on the server-side.
